build:
  image: rust:1.40.0
  only:
    - web
  services:
    - docker:dind
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DB_PASS: testpass
    DB_URL: http://neo4j:testpass@docker:7474/db/data
  cache:
    paths:
      - target/
      - cargo/
  before_script:
    - wget -q https://download.docker.com/linux/static/stable/x86_64/docker-18.09.8.tgz
    - tar -xzf docker-*.tgz
    - cp docker/docker /usr/bin/docker
  script:
    - rustc --version && cargo --version
    - rustup component add clippy
    - cargo clippy --all-targets --all-features -- -D warnings
    - cargo install --list | grep cargo-audit || cargo install cargo-audit
    - cargo audit
    - docker run --rm -d --name neo4j -e NEO4J_AUTH="neo4j/${DB_PASS}" -p 7474:7474 -p 7687:7687 neo4j:3.5
    - cargo test
    - docker rm -f neo4j
    - ls -la
