[package]
name = "warpgrapher"
authors = ["Javier Vazquez"]
description = "Automate web service creation with GraphQL and Neo4J"
homepage = "https://warpforge.github.io/warpgrapher/"
license = "MIT OR Apache-2.0"
repository = "https://github.com/warpforge/warpgrapher"
readme = "README.md"
keywords = ["graphql", "neo4j"]
categories = ["web-programming"]
version = "0.1.1"
edition = "2018"

[features]
graphson2 = ["gremlin-client"]
neo4j = ["r2d2", "r2d2_cypher", "rusted_cypher"]

[dependencies]
# Mandatory dependencies
actix-web = "2.0.0"
env_logger = "0.6.1"
Inflector = "0.11.4"
juniper = "0.13.1"
log = "0.4.6"
num_cpus = "1.0"
reqwest = { version = "0.10.4", features = ["json"] }
serde = { version = "1.0.89", features = ["derive"] }
serde_json = "1.0.39"
serde_yaml = "0.8.8"

# Optional dependencies
gremlin-client = { version = "0.5.0", optional = true }
r2d2 = { version = "0.8.8", optional = true }
r2d2_cypher = { version = "0.4.0", optional = true }
rusted_cypher = { version = "1.1.0", optional = true }

[dev-dependencies]
actix = "0.9.0"
actix-cors = "0.2.0"
actix-http = "1.0.1"
assert_approx_eq = "1.1.0"
futures = "0.3.1"
tokio = { version = "0.2", features = ["rt-threaded", "macros"] }
version-sync = "0.9.0"