[package]
name = "warpgrapher"
authors = ["Javier Vazquez"]
description = "Automate web service creation with GraphQL and Neo4J"
license = "MIT"
repository = "https://github.com/warpforge/warpgrapher"
readme = "README.md"
keywords = ["graphql", "neo4j"]
categories = ["web-programming"]
version = "0.1.1"
edition = "2018"

[features]
graphson2 = ["gremlin-client"]
neo4j = ["r2d2", "r2d2_cypher", "rusted_cypher"]

[dependencies]
# Mandatory dependencies
actix = "0.9.0"
actix-http = "1.0.1"
actix-net = "0.2.6"
actix-rt = "1.0.0"
actix-server-config = "0.1.2"
actix-service = "0.4.1"
actix-threadpool = "0.1.1"
actix-web = "2.0.0"
actix-cors = "0.2.0"
base64 = "0.10.1"
clap = "2.32.0"
env_logger = "0.6.1"
frank_jwt = "3.1.1"
futures = "0.3.1"
indexmap = "1.0.2"
Inflector = "0.11.4"
juniper = "0.13.1"
log = "0.4.6"
num_cpus = "1.0"
regex = "1"
serde = { version = "1.0.89", features = ["derive"] }
serde_json = "1.0.39"
serde_yaml = "0.8.8"
uuid = "0.8.1"
wasm-bindgen = "0.2.33"

# Optional dependencies
gremlin-client = { version = "0.5.0", optional = true }
r2d2 = { version = "0.8.8", optional = true }
r2d2_cypher = { version = "0.4.0", optional = true }
rusted_cypher = { version = "1.1.0", optional = true }

[dev-dependencies]
assert_approx_eq = "1.1.0"
serial_test = "0.3.2"
