version: 1
model:

  # User
  - name: User
    props:
      - name: name
        type: String
        required: true

  # Project
  - name: Project
    props:
      - name: name
        type: String
        validator: NameValidator
      - name: tags
        type: String
        list: true
      - name: points
        type: Int
        #resolver: ProjectPoints
    rels:
      - name: owner
        nodes: [User]
        props: 
          - name: since
            type: String
      - name: board
        nodes: [KanbanBoard, ScrumBoard]
      - name: activity
        nodes: [Commit]
        list: true
      - name: issues
        nodes: [Feature, Bug]
        list: true
      - name: contributors
        nodes: [User]
        list: true
        resolver: ProjectContributors
  
  # Feature
  - name: Feature
    props:
      - name: name
        type: String
  
  # Bug
  - name: Bug
    props:
      - name: name
        type: String
  
  # KanbanBoard
  - name: KanbanBoard
    props:
      - name: name
        type: String
  
  # ScrumBoard
  - name: ScrumBoard
    props:
      - name: name
        type: String
  
  # Commit
  - name: Commit
    props:
      - name: hash
        type: String

  # Metric
  - name: Metric
    props:
      - name: desc
        type: String

endpoints: []

  #ProjectCount
  #- name: ProjectCount
  #  class: Query
  #  input:
  #    list: false
  #    type: ProjectQueryInput
  #  output:
  #    list: false
  #    type: Int
