name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Start neo4j database
      run: docker run --rm -d --name neo4j -e NEO4J_AUTH="neo4j/password123" -p 7474:7474 -p 7687:7687 neo4j:3.5
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
    - name: Stop neo4j database
      run: docker rm -f neo4j
