name: Publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish Crate
      run: cargo publish --dry-run --token $CARGO_TOKEN
    - name: Publish Book
      run: echo "publishing book..."
