name: Publish

on:
  release:
    types:
      - created

jobs:
  test:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
      
    - name: Publish Book
      run: echo "publishing book..."
    
    - name: Publish Crate
      run: echo "publishing crate..."
