name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_URL: http://neo4j:testpass@localhost:7474/db/data
      DB_PASS: testpass
      
    steps:
    - uses: actions/checkout@v2
    
      
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo build
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Cache cargo audit
      uses: actions/cache@v1
      with:
        path: ~/.cargo/bin
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
   
    - name: debug
      run: ls -la ~/.cargo/bin

    - name: debub2
      run: cargo install --list
    
    - name: debug3
      run: echo "some lines" | grep line

    - run: echo $CARGO_INSTALL_ROOT
    - run: echo $CARGO_HOME

    - name: Install Cargo Audit
      run: ls -la ~/.cargo/bin | grep cargo-audit || cargo install cargo-audit
        
    - name: Install Clippy
      run: rustup component add clippy

    - name: Run Linter
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Run Audit
      run: cargo audit
      
    - name: Start neo4j database
      run: docker run --rm -d --name neo4j -e NEO4J_AUTH="neo4j/testpass" -p 7474:7474 -p 7687:7687 neo4j:3.5
    
    - name: Run Tests
      run: cargo test
    
    - name: Stop neo4j database
      run: docker rm -f neo4j
