version: 1
model:

  # User
  - name: User
    props:
      - name: email
        type: String

  # Team
  - name: Team
    props:
      - name: name
        type: String
    rels:
      - name: users
        nodes: [User]